config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get '/home/about' => 'homes#about',as: 'about'

  resources :posts do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    resources :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
 
  has_many :post_comments, dependent: :destroy

  attachment :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/relationship.rb
class Relationship < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  attachment :profile_image
  has_many :post, dependent: :destroy
  has_many :post_comments, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
  end
  
  def destroy
  end
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id

    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)

  end

  def destroy
    PostComment.find_by(id: params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    @post.save
    redirect_to post_path(@post.id)
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def index
    @posts = Post.all
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post.id)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path

  end

  private

  def post_params
    params.require(:post).permit(:title, :caption, :post_image, :jewel, :price, :item, :material, :shop_name)
  end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
  end
  
  def destroy
  end
  
  def followings
  end
  
  def followers
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @posts = @user.post.page(params[:posts_page]).per(6)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def index
    @users = User.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
top

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Jewelog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

     <header>
     <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
       <div class="container">
         <a class="navbar-brand" href="/"><span>Jewelog</span></a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">

       <ul class="navbar-nav ml-auto">

        <% if user_signed_in? %>

         <li>
            <%= link_to user_path(current_user) do %>
              <i class="fas fa-home nav-link text-light"> マイページ</i>
            <% end %>
         </li>
         <li>
           <%= link_to users_path do %>
              <i class="fas fa-users nav-link text-light"> ユーザー</i>
           <% end %>
         </li>
         <li>
           <%= link_to posts_path do %>
              <i class="fas fa-book-open nav-link text-light"> 投稿一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fas fa-sign-out-alt nav-link text-light"> ログアウト</i>
           <% end %>
         </li>
        <% else %>
                 <li>
           <%= link_to root_path do %>
              <i class="fas fa-home nav-link text-light"> Home</i>
           <% end %>
         </li>
         <li>
           <%= link_to about_path do %>
              <i class="fas fa-link nav-link text-light"> About</i>
           <% end %>
         </li>
         <li>
           <%= link_to posts_path do %>
              <i class="fas fa-link nav-link text-light"> 投稿一覧</i>
           <% end %>
         </li>
         <li>
           <%= link_to new_user_registration_path do %>
              <i class="fas fa-user-plus nav-link text-light"> 新規登録</i>
           <% end %>
         </li>
         <li>
           <%= link_to new_user_session_path do %>
              <i class="fas fa-sign-in-alt nav-link text-light"> ログイン</i>
           <% end %>
         </li>

        </ul>

        <% end %>
      </div>
    </div>
  </header>

    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="container ">
  <div class="row">

    <div class="col-md-5 mx-auto mt-3">

     <div class="new mt-3">

      <h2>編集</h2>

       <%= form_with model: @post, local:true do |f| %>

        <div class="form-groupe mb-3">
          <%= f.label :"写真" %>
          <%= f.attachment_field :post_image, placeholder: "投稿画像",class:"form-control-file" %>
        </div>
        <div class="form mb-3">
          <%= f.label :"タイトル" %>
          <%= f.text_field :title, class:"form-control" %>
        </div>
        <div class="form mb-3">
          <%= f.label :"感想" %>
          <%= f.text_area :caption, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :item, 'アイテム' %>
          <%= f.select :item, {'リング': 'リング', 'ネックレス': 'ネックレス', 'ピアス': 'ピアス', 'ブレスレット': 'ブレスレット', 'アンクレット': 'アンクレット', 'ブローチ': 'ブローチ'}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form-group">
          <%= f.label :material, '素材' %>
          <%= f.select :material, {'K18': 'K18', 'K18PG': 'K18PG', 'K18WG': 'K18WG', 'PT': 'PT', 'K10': 'K10', 'K10PG': 'K10PG', 'K10WG': 'K10WG', 'その他の素材': 'その他の素材'}, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form mb-3">
          <%= f.label :"宝石の種類" %>
          <%= f.select :jewel, {'ダイヤモンド': 'ダイヤモンド', 'ルビー': 'ルビー', 'サファイヤ': 'サファイヤ', 'エメラルド': 'エメラルド', 'パール': 'パール', 'アメジスト': 'アメジスト', 'トパーズ': 'トパーズ','トルマリン': 'トルマリン', 'カクテル': 'カクテル', '地金のみ': '地金のみ' }, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form mb-3">
          <%= f.label :"お値段" %>
          <%= f.select :price, {'~ 9999': '~ 9999', '10000 ~ 15000': '10000 ~ 15000', '15000 ~ 20000': '15000 ~ 20000', '20000 ~ 25000': '20000 ~ 25000', '25000 ~ 30000': '25000 ~ 30000', '30000 ~ 40000': '30000 ~ 40000', '40000 ~ 50000': '40000 ~ 50000','50000 ~ 60000': '50000 ~ 60000' }, { include_blank: '選択してください'}, { class: 'form-control' , required: true } %>
        </div>
        <div class="form mb-3">
          <%= f.label :"購入した店舗名" %>
          <%= f.text_area :shop_name, class:"form-control" %>
        </div>

        <div class="actions mb-3">
           <%= f.submit '投稿する', class:"btn btn-sm btn-success" %>
        </div>

       <% end %>
     </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container mt-3">
  <div class="row">

    <div class="col-md-10 mx-auto">

        <h2>投稿一覧</h2>
              <div class="item_container">
                <% @posts.each do |post| %>
                  <div class="item">
                    <%= link_to post_path(post.id) do %>
                     <%= attachment_image_tag post, :post_image, format: "jpeg", fallback: "no_image.jpg", size: "200x200" %>
                     <p><%= post.title %></p>
                    <% end %>
                  </div>

                <% end %>
              </div>

    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container ">
  <div class="row">

      <div class="col-md-5 mt-3">

       <h2>詳細画面</h2>
       <p><%= @post.user.name %>さんの投稿です</p>

         <p><%= attachment_image_tag @post, :post_image, format: "jpeg", fallback: "no_image.jpg", size: "350x350" %></p>



         <p>タイトル：<%= @post.title %></p>
         <p>感想：<%= @post.caption %></p>
         <p>アイテム：<%= @post.item %></p>
         <p>素材：<%= @post.material %></p>
         <p>宝石の種類：<%= @post.jewel %></p>
         <p>お値段：¥<%= @post.price %></p>
         <p>購入した店舗名：<%= @post.shop_name %></p>

           <% if @post.user == current_user %>

                   <td>
                     <%= link_to "編集", edit_post_path(@post), class:"btn btn-sm btn-success" %>
                   </td>
                   <td>
                     <%= link_to "削除", post_path(@post), method: :delete, data:{confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger" %>
                   </td>

           <% end %>
      </div>
       <div class="col-md-5 mt-3">

           <% @post.post_comments.each do |post_comment| %>
             <p><%= attachment_image_tag post_comment.user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "100x100" %></p>
                <%= post_comment.user.name %>
                <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
                <% if post_comment.user == current_user %>
                   <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete %>
                <% end %>

           <% end %>

           <p>コメント件数：<%= @post.post_comments.count %></p>

           <%= form_with(model:[@post, @post_comment], local: true) do |f| %>
             <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに", class:"form-control" %>
             <%= f.submit "送信する" %>
           <% end %>

       </div>


  </div>
</div>

app/views/users/edit.html.erb
<div class="container ">
  <div class="row">

    <div class="col-md-5 mx-auto mt-3">

       <h2>User info</h2>

      <%= form_with model:@user, local:true do |f| %>

       <div class="form-group mb-3">
            <%= f.label :Name %>
            <%= f.text_field :name, class:"form-control" %>
       </div>

          <div class="form-groupe mb-3">
             <%= f.label :Image %>
             <%= f.attachment_field :profile_image, placeholder: "プロフィール画像",class:"form-control-file" %>
          </div>

            <div class="form-group mb-3">
              <%= f.label :Introduction %>
              <%= f.text_field :introduction, class:"form-control" %>
            </div>

               <div class="actions mb-3">
                  <%= f.submit "Update User", class:"btn btn btn-secondary" %>
               </div>


      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container mt-3">
  <div class="row">

    <div class="col-md-10">


        <h2>Users</h2>

        <table class='table table-hover table-inverse'>
          <thead>
            <tr>
              <th>image</th>

              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>

              <tbody>

                <% @users.each do |user| %>
                 <tr>

                   <td><%= attachment_image_tag user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "40x40" %></td>

                   <td><%= user.name %></td>

                   <td><%= link_to "Show",user_path(user) %></td>

                 </tr>
                <% end %>
              </tbody>
          </table>
    </div>
  </div>
</div>

app/views/users/index.js.erb
$('#posts').append("<%= escape_javascript(render 'users/posts', object: @posts) %>");
$("#view_more").replaceWith("<%= escape_javascript(
link_to_next_page(@posts, 'もっと見る', remote: true, id: 'view_more')) %>");

app/views/users/show.html.erb
<div class="container mt-3">

 <div class="row">
   <div class="col-md-5">

     <%= attachment_image_tag @user, :profile_image, format: "jpeg", fallback: "no_image.jpg", size: "130x130" %>
       <table class="table">
        <tbody>
         <tr>
           <th><%= @user.name %></th>
         </tr>
           <th><%= @user.introduction %></th>
         </tr>
         <tr>
           <th>投稿数</th>
           <th></th>
         </tr>
         <tr>
           <th>フォロー中</th>
           <th></th>
         </tr>
         <tr>
           <th>フォロワー</th>
           <th></th>
         </tr>
        </tbody>
       </table>
        <% if @user.id == current_user.id %>
         <div class="row">
          <%= link_to edit_user_path(@user.id), class:"btn btn-outline-secondary btn-block" do %>
      　     <i class="fas fa-user-cog"></i>
          <% end %>
         </div>
        <% end %>
        <%= link_to "ユーザーを探す", users_path %>
        <%= link_to "投稿する", new_post_path %>
   </div>
   <div class="col-md-5">
   　  <h2>自分の投稿</h2>

   　 <div class="col-xs-5 mt-2"><!--col-md-5-->
       <div class="post_container">

          <% @posts.each do |post| %>
           <div class="col-xs-3 offset-md-3 mx-auto">
             <div class="list mr-3">
                <%= link_to post_path(post.id) do %>
                  <%= attachment_image_tag post, :post_image, format: 'jpeg',fallback: "no_image.jpg", size: "150x150", class: 'card-img-top item-target' %><br>
                  <p><%= post.title %></p>
                <% end %>
             </div>
           </div>
          <% end %>

        </div>
     </div>
     <%= paginate @posts, param_name: 'posts_page' %>
   </div>

 </div>
</div>